spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    hibernate:
      ddl-auto: create
      properties:
        hibernate:
        #        show_sql: true   # System out
        show_sql: true
        format_sql: true
        use_sql_comments: true
logging:
  level:
    org.hibernate.SQL: debug    # Logger
    org.hibernate.type: trace   # Show Query Parameter